### PR TITLE
Masterbranch

### PR DESCRIPTION
**Pull request by britboy4321**
Heroku fixes alongside Azure setups and readme updates

### CODE REVIEW

**Comment by britboy4321** [comment]
Pull request covers front end and backend but currently unsuccessful AZURE implementation - azure keeps saying app crashed.

Secrets stored correctly, security implemented (but not Azure yet)

**Comment by haris1998-web** [comment]
https://github.com/britboy4321/E0TestingApp/blob/main/todo_app/templates/indexread.html

UI seems unclear and has unnecessary information - such as field names repeated in title and header

https://github.com/britboy4321/E0TestingApp/blob/main/todo_app/templates/indexwrite.html

Same problems as indexread.html


https://github.com/britboy4321/E0TestingApp/blob/main/todo_app/templates/indexwrite.html

Why is this file here?  It is not used.

https://github.com/britboy4321/E0TestingApp/blob/main/todo_app/app.py

has comments all over the place that are simply unnecessary in my opinion and needs substancial tidying up

**Comment by britboy4321** [comment]
UI - clarity fixed.  

Indexread.html and Indexwrite.html    field names reduced - repeating information removed.

Logging picture will remain, as potentially useful (as reference) for future implementation of Dynatrace.

Many comments removed from app.py

Thanks.

**Comment by haris1998-web** [comment]
Now it looks great we can merge the code now

**Pull request merged**
